title: Dinky theme
description: Dinky is a red hot theme for GitHub Pages.
theme: jekyll-theme-dinky
github:
  is_project_page: false
  exe_url: https://github.com/wanghai1988/QTGA/releases/download/v0.1/QTGA.zip